services:
  - type: web
    name: libretranslate
    env: docker
    plan: free
    branch: main
    dockerContext: .
    dockerfilePath: Dockerfile
    ports:
      - port: 5000
        protocol: http
